"""empty message

Revision ID: 939028f84216
Revises: a896d700c783
Create Date: 2024-04-21 15:35:58.518155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939028f84216'
down_revision = 'a896d700c783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=80), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('crew', sa.String(length=80), nullable=True),
    sa.Column('lenght', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('max_speed', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('passengers', sa.String(length=80), nullable=True),
    sa.Column('vehicle_class', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
