"""empty message

Revision ID: c8b6643c5e86
Revises: cfd91ad81f7b
Create Date: 2024-04-21 15:42:58.366287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b6643c5e86'
down_revision = 'cfd91ad81f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_vehicles')
    # ### end Alembic commands ###
