"""empty message

Revision ID: cff76b3c9b57
Revises: 6978e6c80f1c
Create Date: 2024-06-11 11:04:13.923934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff76b3c9b57'
down_revision = '6978e6c80f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=True))
        batch_op.drop_column('id')
        batch_op.drop_column('language')
        batch_op.drop_column('designation')
        batch_op.drop_column('lifespan')
        batch_op.drop_column('classification')

    with op.batch_alter_table('favorites_characters', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_characters_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['uid'])

    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_planets_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['uid'])

    with op.batch_alter_table('favorites_vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_vehicles_vehicle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['uid'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vehicle_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('uid')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('planet_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('uid')

    with op.batch_alter_table('favorites_vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_vehicles_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_planets_planet_id_fkey', 'planet', ['planet_id'], ['id'])

    with op.batch_alter_table('favorites_characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_characters_character_id_fkey', 'character', ['character_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lifespan', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('character_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('url')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
